import type { FleetStat, Inspection } from "./types";

export const ORG_NAME = "Midwest Freight Co.";
export const USER_INITIALS = "MF";

export const fleetStats: FleetStat[] = [
  {
    id: "active",
    label: "Active trucks",
    value: "94",
    icon: "truck",
    trendLabel: "6 since last week",
    trendKind: "up",
  },
  {
    id: "today",
    label: "Inspections today",
    value: "17",
    icon: "clipboard",
    trendLabel: "8 pending · 9 complete",
    trendKind: "neutral",
  },
  {
    id: "findings",
    label: "Open findings",
    value: "23",
    icon: "alert",
    trendLabel: "4 new this inspection",
    trendKind: "alert",
  },
  {
    id: "avg",
    label: "Avg inspection time",
    value: "4.2m",
    icon: "clock",
    trendLabel: "38% vs manual",
    trendKind: "down",
  },
];

export const inspections: Inspection[] = [
  {
    id: "insp-041",
    truckId: "TRK-041",
    make: "Freightliner",
    model: "Cascadia",
    capturedAtLabel: "Today, 9:14 AM",
    relativeLabel: "6 min ago",
    source: "mobile",
    status: "complete",
    findings: [
      {
        id: "f-1",
        title: "Structural dent",
        type: "dent",
        severity: "critical",
        location: "Rear passenger corner",
        confidence: 0.94,
        zone: "trailer_rear",
        firstDetectedInspectionsAgo: 0,
      },
      {
        id: "f-2",
        title: "Paint scratch",
        type: "scratch",
        severity: "medium",
        location: "Driver side panel",
        confidence: 0.87,
        zone: "trailer_mid",
        firstDetectedInspectionsAgo: 3,
      },
      {
        id: "f-3",
        title: "Mirror misalignment",
        type: "anomaly",
        severity: "low",
        location: "Passenger side mirror",
        confidence: 0.79,
        zone: "cab",
        firstDetectedInspectionsAgo: 1,
      },
    ],
  },
  {
    id: "insp-017",
    truckId: "TRK-017",
    make: "Kenworth",
    model: "T680",
    capturedAtLabel: "Today, 8:51 AM",
    relativeLabel: "29 min ago",
    source: "mobile",
    status: "complete",
    findings: [
      {
        id: "f-4",
        title: "Surface rust",
        type: "rust",
        severity: "medium",
        location: "Front bumper",
        confidence: 0.82,
        zone: "front",
        firstDetectedInspectionsAgo: 5,
      },
      {
        id: "f-5",
        title: "Tire sidewall wear",
        type: "anomaly",
        severity: "low",
        location: "Front driver axle",
        confidence: 0.71,
        zone: "front",
        firstDetectedInspectionsAgo: 2,
      },
    ],
  },
  {
    id: "insp-088",
    truckId: "TRK-088",
    make: "Peterbilt",
    model: "579",
    capturedAtLabel: "Today, 8:22 AM",
    relativeLabel: "58 min ago",
    source: "mobile",
    status: "complete",
    findings: [
      {
        id: "f-6",
        title: "Cracked headlight",
        type: "crack",
        severity: "critical",
        location: "Driver side front",
        confidence: 0.9,
        zone: "front",
        firstDetectedInspectionsAgo: 0,
      },
    ],
  },
  {
    id: "insp-062",
    truckId: "TRK-062",
    make: "Volvo",
    model: "VNL 860",
    capturedAtLabel: "Today, 7:58 AM",
    relativeLabel: "1h 22m ago",
    source: "mobile",
    status: "complete",
    findings: [],
  },
  {
    id: "insp-033",
    truckId: "TRK-033",
    make: "Mack",
    model: "Anthem",
    capturedAtLabel: "Yesterday, 5:44 PM",
    relativeLabel: "yesterday",
    source: "mobile",
    status: "complete",
    findings: [
      {
        id: "f-7",
        title: "Trailer panel dent",
        type: "dent",
        severity: "medium",
        location: "Mid trailer, driver side",
        confidence: 0.85,
        zone: "trailer_mid",
        firstDetectedInspectionsAgo: 4,
      },
    ],
  },
];
